name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          # Additional dependencies if needed

      - name: Run automated tests
        run: |
          pytest test.py

  push-to-test:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ needs.build-and-test.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Push to test branch
        run: |
          git checkout -b test
          git add .
          git commit -m "Automated push from dev"
          git push origin test

  merge-to-master:
    runs-on: ubuntu-latest
    needs: push-to-test
    if: ${{ needs.push-to-test.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test

      - name: Merge to master
        run: |
          git checkout master
          git pull origin master
          git merge --no-ff test
          git push origin master
