name: Automated Testing and Deployment

on:
  push:
    branches:
      - dev

jobs:
  create-test-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request to merge dev into test
        uses: peter-evans/create-pull-request@v3
        with:
          base: test
          head: dev
          title: "Merge dev into test"
          body: "Automatically created pull request from dev to test."

  automated-testing:
    runs-on: ubuntu-latest
    needs: create-test-pull-request
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install Flask
          # Additional dependencies if needed

      - name: Run automated tests on test branch
        run: |
          pytest test.py

  merge-to-master:
    runs-on: ubuntu-latest
    needs: automated-testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test

      - name: Merge to master if tests pass
        if: ${{ needs.automated-testing.result == 'success' }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout master
          git pull origin master
          git merge --no-ff test
          git push origin master
